// 按需全局引入 vant组件
import Vue from 'vue'
import { Button, List, Cell, Tabbar, TabbarItem,Form,Image as VanImage,Icon,Field,Checkbox, CheckboxGroup,NavBar,Dialog,Popup,Picker,Col, Row, CellGroup,Uploader,
    PullRefresh,Toast,Calendar,Tab, Tabs,RadioGroup, Radio,NumberKeyboard,DatetimePicker,Area,ActionSheet,ImagePreview,Loading,Skeleton  } from 'vant'
Vue.use(Button)
Vue.use(Cell)
Vue.use(List)
Vue.use(Tabbar).use(TabbarItem)
Vue.use(Form)
Vue.use(VanImage)
Vue.use(Icon)
Vue.use(Field)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(NavBar)
Vue.use(Dialog)
Vue.use(Popup)
Vue.use(Picker)
Vue.use(Col)
Vue.use(Row)
Vue.use(CellGroup)
Vue.use(Uploader)
Vue.use(PullRefresh)
Vue.use(Toast)
Vue.use(Calendar)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Radio)
Vue.use(RadioGroup)
Vue.use(NumberKeyboard)
Vue.use(DatetimePicker)
Vue.use(Area)
Vue.use(ActionSheet)
Vue.use(ImagePreview)
Vue.use(Loading)
Vue.use(Skeleton)